name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test:ci

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload coverage reports
        if: success() && github.event_name == 'push'
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
